name: 'Push images'
on:
  push:
    branches:
      - main

#workflow_dispatch:
#Permet de lancer le workflow manuellement

jobs:
  push_to_registry:
    name: 'Push Docker image to Docker Hub'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the repo'
        uses: actions/checkout@v2
      
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: 'Build Docker images'
        run: docker build . --file Dockerfile --tag 260219010608/guestbook:$GITHUB_SHA
        working-directory: ./guestbook

      - name: 'Push Docker images'
        run: docker push 260219010608/guestbook:$GITHUB_SHA
        working-directory: ./guestbook

      - name: 'Google auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v0

      - name: 'Use gcloud CLI'
        run: gcloud container clusters get-credentials cluster-1 --zone europe-west1-b --project kubernetes-187222

      - name: 'Install Kubectl'
        uses: azure/setup-kubectl@v2.0

      - name: 'Apply all YAML'
        run: kubectl apply -f ./deploy