name: 'Push images'
on:
  push:
    branches:
      - main

#workflow_dispatch:

default:
  run:
    working-directory: ./guestbook

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker images
        run: docker buid . --file Docker --tag dylan-picquendar/guestbook:$GITHUB_SHA

      - name: Push Docker images
        run: docker push dylan-picquendar/guestbook:$GITHUB_SHA



#      - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1
#
#     - name: Push to Docker Hub
#        uses: docker/build-push-action@v1
#        with:
#          repository: dylan-picquendar/guestbook
#          tag_with_sha: true
#          dockerfile: guestbook/Dockerfile
